### ISSUE TITLE
How to bundle it in web apps?

### ISSUE THREAD

**Issue by yb6b** [kitschpatrol/yanki-connect#2]
Hello, I attempted to integrate Yanki-Connect into a Vite project. However, an error occurred:

```
error during build:
node_modules/.pnpm/default-browser-id@5.0.0/node_modules/default-browser-id/index.js (1:8): "promisify" is not exported by "__vite-browser-external", imported by "node_modules/.pnpm/default-browser-id@5.0.0/node_modules/default-browser-id/index.js".
``` 

I discovered that Yanki-Connect imports 'open', which is exclusive to Node.js. Think removing the autoLaunch functionality would settle this issue. Is there a better way?

**Comment by kitschpatrol** [comment]
Hi thanks for trying the library and taking the time to open an issue.

It looks like even though the Node-specific launching logic is [behind a dynamic import](https://github.com/kitschpatrol/yanki-connect/blob/main/src/utilities/launcher.ts#L9-L10), Vite is not tree-shaking it away on build.

However, I'm able to get a Vite project with `yanki-connect` building correctly with the following `vite.config.ts`:

```ts
import { defineConfig } from "vite";

export default defineConfig({
  build: {
    rollupOptions: {
      external: ["open"],
    },
  },
});
```

Let me know if that works for you, and if you'd like a full project example.

I'll see if there are better ways to get Vite to ignore the Node-specific functionality without placing the burden of configuration on the library user, but in the meantime will add a note to the readme if this is a fix for you.

**Comment by yb6b** [comment]
Thanks, your approach works! And think it's helpful to add this note to README.md.

**Comment by kitschpatrol** [comment]
Great! Added a section to the readme with instructions.
